### PR TITLE
Updated tracks to use new shortlist of tracks.

### PR DESCRIPTION
**Pull request by kylekirkby**
Updated tracks to use new shortlist of tracks.
Updated with:
https://gist.github.com/kylekirkby/89d693eafe079a9e14e6d18330d3d9dd

### CODE REVIEW

**Review by pcolmer — APPROVED** [review]

**Comment by kylekirkby** [comment]
Needs some updates since some tracks are being replaced with the wrong "new" track.

**Comment by kylekirkby** [comment]
@pcolmer, I've updated this branch so that the tracks of sessions are added to the tags front matter list. `Keynote` was being removed in favour of `None/Other` yet we are still going to want to find all the keynote sessions.

**Comment by pcolmer** [comment]
> yet we are still going to want to find all the keynote sessions.

So why are we tagging the keynotes as "None/Other"?

I think that Marketing need to sign off on this, rather than me. If Marketing do not want or need a way to find Keynote sessions, that's fine. If they do, then the sessions need to be tagged appropriately.

**Comment by kylekirkby** [comment]
> > yet we are still going to want to find all the keynote sessions.
> 
> So why are we tagging the keynotes as "None/Other"?
> 
> I think that Marketing need to sign off on this, rather than me. If Marketing do not want or need a way to find Keynote sessions, that's fine. If they do, then the sessions need to be tagged appropriately.

I was just thinking that to be honest. @EbbaSimpson why has the keynote track been removed?

**Comment by kylekirkby** [comment]
@pcolmer, I've updated the PR so that only sessions that had the `Keynote` track (which is now None/Other) has had the `Keynote` tag added. Waiting on a response from @EbbaSimpson.

**Pull request merged**
