### PR TITLE
Create Pages “connectfaqs”

### PR DESCRIPTION
**Pull request by kristinedill**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by pcolmer** [comment]
There is a broken link in the sitemap:

/sitemap/index.html:
   /ConnectFAQs

I'll leave that for @kylekirkby to investigate further :).

**Comment by kylekirkby** [comment]
> There is a broken link in the sitemap:
> 
> /sitemap/index.html:
> /ConnectFAQs
> 
> I'll leave that for @kylekirkby to investigate further :).

@kristinedill - can you update the permalink to use the /connect-faqs/ format (with trailing slash)?

**Comment by kristinedill** [comment]
@kylekirkby I can't see the FAQ page now in the list on Netlify?

**Comment by kylekirkby** [comment]
> @kylekirkby I can't see the FAQ page now in the list on Netlify?

Stange... it shows under workflow for me? Try a refresh or an Incognito window?

**Comment by kristinedill** [comment]
thanks @kylekirkby that worked. I've just updated the permalink

**Comment by kylekirkby** [comment]
> thanks @kylekirkby that worked. I've just updated the permalink

Awesome - just looking at the new page and NetlifyCMS is adding some empty defaults. So not 100% certain this will as expected. I'll check the deploy preview and then, if necessary, update the NetlifyCMS config so that this works!!

**Comment by kristinedill** [comment]
ok thank you! it asked me to provide a layout and suggested "flow" so that's what I typed.. this was my first attempt at creating a page so I may have missed something.. @kylekirkby

**Comment by kylekirkby** [comment]
> ok thank you! it asked me to provide a layout and suggested "flow" so that's what I typed.. this was my first attempt at creating a page so I may have missed something.. @kylekirkby

As expected... http://staging-connect-linaro-org-361.websitepreview.linaro.org/connect-faq/
I'll look into this now!

**Comment by kylekirkby** [comment]
> ok thank you! it asked me to provide a layout and suggested "flow" so that's what I typed.. this was my first attempt at creating a page so I may have missed something.. @kylekirkby

Hi @kristinedill,

Could you please try and create the page again? I've updated the NetlifyCMS config to remove uneccessary front matter from new pages. See my [test-page](https://github.com/Linaro/Connect/pull/363/files) :)

Regards,

Kyle

**Comment by kristinedill** [comment]
> > ok thank you! it asked me to provide a layout and suggested "flow" so that's what I typed.. this was my first attempt at creating a page so I may have missed something.. @kylekirkby
> 
> Hi @kristinedill,
> 
> Could you please try and create the page again? I've updated the NetlifyCMS config to remove uneccessary front matter from new pages. See my [test-page](https://github.com/Linaro/Connect/pull/363/files) :)
> 
> Regards,
> 
> Kyle

Hi @kylekirkby I just tried creating the FAQ page again. Thanks!

**Comment by kristinedill** [comment]
@kylekirkby I created a completely new FAQ page - was I supposed to just try to save this existing page again?...

**Pull request closed without merging**
