### PR TITLE
Connect Homepage / Theme Updates

### PR DESCRIPTION
**Pull request by kylekirkby**
Connect Homepage / Theme Updates

### CODE REVIEW

**Review by pcolmer — APPROVED** [review]

**Comment by Jon-Burcham** [comment]
Currently states "We are now accepting proposals for sessions at LVC21. Visit our CFP page for more information." Need to update before merging.

**Comment by kylekirkby** [comment]
> Currently states "We are now accepting proposals for sessions at LVC21. Visit our CFP page for more information." Need to update before merging.

What should it be updated with?

**Comment by Jon-Burcham** [comment]
Please remove that box and text and re-centre the box with the text and date. This box can also be made 25% bigger if it is a quick fix. 

Thanks Jon

**Comment by kristinedill** [comment]
Hi @kylekirkby can we change that box to say 
"The full schedule will be announced and registration will open on 26 January" 

Thanks!

**Comment by kristinedill** [comment]
Hi Kyle,

Just chatted with JOn
Can we actually keep the box and edit it to say
"The full schedule will be announced and registration will open on 26
January"

Thank you!


Kristine Dill |  Events Manager
Cell: +19789940106 |
Skype: kristine.dill1

**Comment by kylekirkby** [comment]
@kristinedill @Jon-Burcham - I've updated as requested.

**Comment by kristinedill** [comment]
Hi @kylekirkby I can't seem to find the text box to update this on Netlify under the "bringing together the Arm ecosystem" page. 

The text reads a bit awkward could you please update this to say:

"The full schedule and registration will be announced January 26, 2021" 

Thank you

**Comment by kylekirkby** [comment]
> Hi @kylekirkby I can't seem to find the text box to update this on Netlify under the "bringing together the Arm ecosystem" page.
> 
> The text reads a bit awkward could you please update this to say:
> 
> "The full schedule and registration will be announced January 26, 2021"
> 
> Thank you

Hi @kristinedill,

You wouldn't be able to since I created this PR by means other than Netlify. I'll update my PR.

Cheers! 

Kyle

**Review by kristinedill — APPROVED** [review]

**Pull request merged**
