### PR TITLE
Latest netlifycms updates

### PR DESCRIPTION
**Pull request by kylekirkby**
Latest netlifycms updates
- Removed old pages (AI / Arm on Arm summits)
- Added the _data/featured_keynotes.yml file to netlifycms config
- Added SAN19 posts to netlifycms config
- Demo Friday page updated to use the flow layout
- Moved the homepage (index.md) to the _pages folder so that it can be edited via netlifycms

### CODE REVIEW

**Comment by pcolmer** [comment]
@kylekirkby are you forgetting to reset your develop branch so that the commit only includes explicitly the files you've changed? @morancj and myself are being asked to review this as codeowners because an *earlier commit* touched Gemfile but this specific PR doesn't.

I've inclined to reject it on that basis alone :)

**Comment by kylekirkby** [comment]
> @kylekirkby are you forgetting to reset your develop branch so that the commit only includes explicitly the files you've changed? @morancj and myself are being asked to review this as codeowners because an _earlier commit_ touched Gemfile but this specific PR doesn't.
> 
> I'm inclined to reject it on that basis alone :)

Yes I think I forgot to merge changes from linaro/connect:develop into my local branch and resolved via the GitHub UI instead :) - sorry!

**Comment by pcolmer** [comment]
What do you think, @morancj? Let him off or make him submit a new, clean PR?

**Comment by pcolmer** [comment]
image

Ha ha ha ha ha!

**Pull request merged**
